select x.cdate, x.tag, count(id) as cnt
  from (
select id, cast(creationdate as date) as cdate, 
        case when tags like '%<.net>%' then '.net' when tags like '%<amazon-web-services>%' then 'amazon-web-services' when tags like '%<android>%' then 'android' when tags like '%<angular>%' then 'angular' when tags like '%<api>%' then 'api' when tags like '%<arrays>%' then 'arrays' when tags like '%<azure>%' then 'azure' when tags like '%<c>%' then 'c' when tags like '%<c#>%' then 'c#' when tags like '%<c++>%' then 'c++' when tags like '%<css>%' then 'css' when tags like '%<dart>%' then 'dart' when tags like '%<dataframe>%' then 'dataframe' when tags like '%<django>%' then 'django' when tags like '%<docker>%' then 'docker' when tags like '%<excel>%' then 'excel' when tags like '%<firebase>%' then 'firebase' when tags like '%<flutter>%' then 'flutter' when tags like '%<html>%' then 'html' when tags like '%<ios>%' then 'ios' when tags like '%<java>%' then 'java' when tags like '%<javascript>%' then 'javascript' when tags like '%<jquery>%' then 'jquery' when tags like '%<json>%' then 'json' when tags like '%<kotlin>%' then 'kotlin' when tags like '%<laravel>%' then 'laravel' when tags like '%<linux>%' then 'linux' when tags like '%<list>%' then 'list' when tags like '%<mongodb>%' then 'mongodb' when tags like '%<mysql>%' then 'mysql' when tags like '%<next.js>%' then 'next.js' when tags like '%<node.js>%' then 'node.js' when tags like '%<numpy>%' then 'numpy' when tags like '%<pandas>%' then 'pandas' when tags like '%<php>%' then 'php' when tags like '%<postgresql>%' then 'postgresql' when tags like '%<python>%' then 'python' when tags like '%<python-3.x>%' then 'python-3.x' when tags like '%<r>%' then 'r' when tags like '%<react-native>%' then 'react-native' when tags like '%<reactjs>%' then 'reactjs' when tags like '%<spring>%' then 'spring' when tags like '%<spring-boot>%' then 'spring-boot' when tags like '%<sql>%' then 'sql' when tags like '%<sql-server>%' then 'sql-server' when tags like '%<swift>%' then 'swift' when tags like '%<typescript>%' then 'typescript' when tags like '%<vba>%' then 'vba' when tags like '%<visual-studio-code>%' then 'visual-studio-code' when tags like '%<vue.js>%' then 'vue.js'
             end as tag 
   from postswithdeleted 
   where creationdate between '2022-10-05' and '2023-03-14'
    and posttypeid = '1'
    and (tags like '%<.net>%' or tags like '%<amazon-web-services>%' or tags like '%<android>%' or tags like '%<angular>%' or tags like '%<api>%' or tags like '%<arrays>%' or tags like '%<azure>%' or tags like '%<c>%' or tags like '%<c#>%' or tags like '%<c++>%' or tags like '%<css>%' or tags like '%<dart>%' or tags like '%<dataframe>%' or tags like '%<django>%' or tags like '%<docker>%' or tags like '%<excel>%' or tags like '%<firebase>%' or tags like '%<flutter>%' or tags like '%<html>%' or tags like '%<ios>%' or tags like '%<java>%' or tags like '%<javascript>%' or tags like '%<jquery>%' or tags like '%<json>%' or tags like '%<kotlin>%' or tags like '%<laravel>%' or tags like '%<linux>%' or tags like '%<list>%' or tags like '%<mongodb>%' or tags like '%<mysql>%' or tags like '%<next.js>%' or tags like '%<node.js>%' or tags like '%<numpy>%' or tags like '%<pandas>%' or tags like '%<php>%' or tags like '%<postgresql>%' or tags like '%<python>%' or tags like '%<python-3.x>%' or tags like '%<r>%' or tags like '%<react-native>%' or tags like '%<reactjs>%' or tags like '%<spring>%' or tags like '%<spring-boot>%' or tags like '%<sql>%' or tags like '%<sql-server>%' or tags like '%<swift>%' or tags like '%<typescript>%' or tags like '%<vba>%' or tags like '%<visual-studio-code>%' or tags like '%<vue.js>%')
    )x 
group by x.cdate, x.tag 
order by x.cdate